### ISSUE TITLE
Compilation errors are only shown after first hot swap

### ISSUE THREAD

**Issue by s-panferov** [basti1302/elm-reactor-custom-html#2]
I don't see any compilation errors when I open a page. I see them only if I change something in my code. Is there any solution for this problem?

**Comment by basti1302** [comment]
That's true. Here are the reasons, as far as I understand them:
- When you build your Elm sources via elm-make, the resulting elm.js contains the Elm runtime as well as your compiled custom Elm code.
- You need to have a script tag for the elm.js in index.debug.html, otherwise the Elm runtime is missing.
- Thus, you need to compile your stuff with elm-make once successfully before starting elm-reactor, so that the elm.js bundle with the Elm runtime exists in the file system. In this setup this is done in the npm postinstall hook.
- From there on, if you use elm-reactor and change the source code, elm-reactor notices this and recompiles the code.

Now, if you introduce compile errors into your source code **between that last successful elm-make run and accessing the page via elm-reactor**, the file `elm.js` still exists on disk and can be loaded, but elm-reactor can not recompile your stuff. I think this is what happens and why you only see compile errors when you change your code, while the page is opened in the browser.

**Comment by basti1302** [comment]
If you have an idea how to change this setup to improve things, that would be A+. I suspect that changes in elm-reactor are required here.
